# path
path:
  #resume_state: checkpoints/states/750.state # path to the state file for resuming training
  resume_state: 
  pretrain_G:   # path to the pre-trained generator if exists
  log: logs
  tb_logger: tb_logger
  checkpoints:
    models: checkpoints/models
    states: checkpoints/states
    val_image_dir: checkpoints/val_results

# dataset
datasets:
  train:
    name: REALSR
    BIC_dir: /content/drive/MyDrive/Colab Notebooks/dataset/Train/BIC_LR
    REAL_dir: /content/drive/MyDrive/Colab Notebooks/dataset/Train/REAL_LR
    batch_size: 16
    shuffle: True
    patch: 128
    flip: True
    rotation: True
    n_workers: 8
  valid:
    name: REALSR
    testY: True
    BIC_dir: /content/drive/MyDrive/Colab Notebooks/dataset/Test/RealSR/LR
    REAL_dir: /content/drive/MyDrive/Colab Notebooks/dataset/Test/RealSR/REAL_LR

# networks
network_G:
  mode: CNA
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 8
  gc: 32
  scale: 1
  norm_type:
  act_type: relu

network_D:
  mode: CNA
  norm_type: batch
  act_type: leakyrelu
  in_nc: 3
  base_nf: 64

# training details

train:
  lr_G: 0.0001
  lr_D: 0.0001

  b1_G: 0.9
  b2_G: 0.999
  b1_D: 0.9
  b2_D: 0.999

  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  wt_pix: 1
  wt_fea: 3
  wt_gan: 1

  niter: 500000
  val_freq: 20

  save_step: 50
  print_freq: 5
